version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_URL=mysql+mysqlconnector://jayesh:12345678@mysql:3306/employeePrediction
    networks:
      - app-network
    depends_on:
      - mysql

  frontend:
    build:
      context: ./employee_prediction
    ports:
      - "8000:8000"
    environment:
      - BASE_URL=http://backend:5001
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: jayesh
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: employeePrediction
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
